name: Docker Build and Push & Vercel Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push back-end image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: samigonza3/back-end:latest

      - name: Build and push front-end image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: samigonza3/front-end:latest

  deploy-to-vercel:
    runs-on: ubuntu-latest
    needs: build-and-push
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token ${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token ${{ secrets.VERCEL_TOKEN }}